# Generated by Django 4.2 on 2023-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myelections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='position',
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='member_images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
